#服务器的配置
server:
  port: 8888

book:
  name: 三国演义
  author: 罗贯中
  price: 30
  description: ${book.name}的价格是${book.price}
  fans:
    - aa
    - bb
    - cc
  rank:
    january: 1
    february: 2
    march: 3